### ISSUE TITLE
No release information

### ISSUE THREAD

**Issue by broomfn** [datalust/helm.datalust.co#13]
I'm trying to get the first use username/password hash set, but it's not working, I can see from the commit history this was only added to the chart in mid April, how can I see the release or chart version this update made it in to?

**Comment by broomfn** [comment]
I'm guessing as 2021.2.5647 was out on the 12th of April and the chart didn't get updating until the 15 that I didn't make the cut. Would be useful to be able to see what commits are in what release though.

**Comment by nblumhardt** [comment]
Thanks for the note! We're just getting the release process for this chart nailed down, now; we'll make sure to signal the contents of the next one (2021.3.x) somewhere conspicuous 👍
