### ISSUE TITLE
if specify memory limits, there is an error

### ISSUE THREAD

**Issue by toorsunov** [datalust/helm.datalust.co#14]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/35526267/126866629-aecb1f1e-ec87-47e4-a9b9-b727f11dc60c.png">
<img width="762" alt="image" src="https://user-images.githubusercontent.com/35526267/126866644-b698a7fe-cd5a-434f-9d75-77c12db4d507.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/35526267/126866650-14330368-84e2-4c13-82e3-13477b4342a5.png">
And I have a second question: How to specify CPU limits?
Thank you in advance

Respectfully,
Jamshid Tursunov

**Comment by KodrAus** [comment]
Hi @toorsunov 👋 

Sorry our docs are a little unclear here. You’ll need to remove the `{}` characters too if you uncomment the `limits` property.

You can specify CPU limits by adding a `cpu` property alongside `memory`, such as `cpu: 2`.

Theres some more details on memory and CPU limits in the Kubernetes docs too: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

**Comment by KodrAus** [comment]
It's been a little while now so I'll go ahead and close this one, but if you have any more questions please feel free to open new issues!
