### ISSUE TITLE
rendered ingress manifest has a blank line after "rules"

### ISSUE THREAD

**Issue by KenWestgate** [datalust/helm.datalust.co#15]
There appears to be a missing left chomp - on line 31: {{ if .Values.ui.ingress.enabled }} of
of https://github.com/datalust/helm.datalust.co/blob/main/charts/seq/templates/ingress.yaml

This leads to rendered manifests with a blank line after "rules"

Line 31 should read:
{{- if .Values.ui.ingress.enabled }}

**Comment by nblumhardt** [comment]
Thank you, Ken - fixed now 👍 The fix should be out with the next maintenance release - are you blocked on this in the meantime?

**Comment by KenWestgate** [comment]
Excellent, thanks for the very quick fix Nicholas.
There's no block so the next maintenance release will be absolutely fine thank you.
