### ISSUE TITLE
Add an option to set SEQ_METASTORE environment variables

### ISSUE THREAD

**Issue by jufa2401** [datalust/helm.datalust.co#21]
In our workload we would like to use the datastore which is supported through seq's environment variables, however it does not seem to be exposed through this helm chart, specifically we're using the SEQ_METASTORE_POSTGRES_CONNECTIONSTRING.

Version:  2021.3.6800

Is it possible that this option can be exposed in the future?

**Comment by nblumhardt** [comment]
Thanks for the note! We should definitely make it easier/simpler to set arbitrary environment variables on the Seq container through the chart :+1:

If you're able to initialize the mounted data volume with some files, you should be able to work around this one today using an [init script](https://docs.datalust.co/docs/init-scripts):

```sh
echo "connection string here" | seqsvr secret set -v metastore.postgres.connectionString --value-stdin
```

Let me know if it seems like this could be an option/if you need more info.

**Comment by jufa2401** [comment]
Thanks, I suppose that does suffice for now for our workload. 👍
