### ISSUE TITLE
Release 2021.4.6986 not available as helm chart

### ISSUE THREAD

**Issue by codedevote** [datalust/helm.datalust.co#22]
I just wanted to upgrade via helm chart and found that the helm repo at helm.datalust.co does not contain the latest version 2021.4.6986. Though the Github release says "Published to helm.datalust.co.". Am I missing something?

**Comment by nblumhardt** [comment]
Thanks for the heads-up, Florian. It looks as if something failed and was unnoticed in the deployment process; digging in now.

**Comment by nblumhardt** [comment]
This is published now - thanks again for letting us know! If you run into any more difficulties, please don't hesitate to get in touch.
