### ISSUE TITLE
Make first run admin user and password hash configurable

### ISSUE THREAD

**Issue by codedevote** [datalust/helm.datalust.co#3]
I create this issue with reference to a discussion here: https://github.com/datalust/seqcli/issues/188. 

There should be a possibility to set `SEQ_FIRSTRUN_ADMINUSERNAME` and `SEQ_FIRSTRUN_ADMINPASSWORDHASH` for the helm chart through passing appropriate values.yaml.

**Comment by nblumhardt** [comment]
Merged in #4
