### ISSUE TITLE
Please add support for imagePullSecrets

### ISSUE THREAD

**Issue by prochnowc** [datalust/helm.datalust.co#5]
In our deployments we use a proxy container registry which requires the use of credentials.
Can you please add support for 'imagePullSecrets' in the 'Values' ?

**Comment by prochnowc** [comment]
@KodrAus Thanks! That was fast ... when can I expect a new chart release ? I would like to consume this (and the recently added support for initial admin user/pw).

**Comment by nblumhardt** [comment]
@prochnowc this will ship with Seq 2021.3, which we're aiming to have out in around two months. In the meantime - is it possible to grab the files from this repo directly, and deploy the chart that way?
